### ISSUE TITLE
The CP System sound to loud

### ISSUE THREAD

**Issue by Josmar34** [ValleyBell/vgmplay-libvgm#1]
I know before I saythis, but the new version with the Street Fighter II Champion Edition, the OKIM6295 sound to strong, the YM2151 sound so to low. I will try setting the Chip Sample Mode, which is by default at 3, but if no configuration change gives me the audio balance I am looking for, I am afraid it will be another configuration problem.

**Comment by ValleyBell** [comment]
This is a currently known "bug" from libvgm. see https://github.com/ValleyBell/libvgm/issues/63

**Comment by ValleyBell** [comment]
fixed by fixing the respective VGM packs to not require a hack anymore
