### ISSUE TITLE
Max Loops doesn't seem to work?

### ISSUE THREAD

**Issue by Nicholas-Steel** [ValleyBell/vgmplay-libvgm#12]
I set it to 100 but it seems the Player quits long before it hits the 100th loop of the song, for some tracks the song plays only once before the Player closes. I get the impression some aspect of the music files is overriding the loop function.

For example, the Konami Logo file from https://www.zophar.net/music/sega-mega-drive-genesis/castlevania-bloodlines-[castlevania-the-new-generation] only plays once.

Is there a way to make it loop indefinitely?

**Comment by ValleyBell** [comment]
Songs that are not intended to loop will not loop.

Such songs, for example:
```
Format:         VGM 1.50    Gain: 1.00    Loop: No
```

Max Loops affects only songs that are intended to loop.
```
Format:         VGM 1.50    Gain: 1.00    Loop: Yes (01:43.68)
```

**Comment by Nicholas-Steel** [comment]
So no way to override that behaviour?

**Comment by ValleyBell** [comment]
There or no way to make non-looping songs (like the Konami Logo) loop, because they are *not intended* to loop.
(same issue as ValleyBell/libvgm#94)

If you want that, you will need to retrim the VGM so that it loops.
