### ISSUE TITLE
add support for dumping file info

### ISSUE THREAD

**Issue by RiedleroD** [ValleyBell/vgmplay-libvgm#15]
things like
- which chip is used
- whether it loops and if so, at what point
- how many channels there are

I could really use that info for my project [newdump](https://codeberg.org/Riedler/newdump/), although for now I will attempt reading the file on my own, as shown [here](https://gist.github.com/txmutt/308109b6e595c990832c8fe5cbf20806). I'm really not a fan of duplicated code though, especially when it comes to reading file formats (who knows what bugs I could introduce there)

**Comment by ValleyBell** [comment]
For these things you should probably just use the [libvgm backend](https://github.com/ValleyBell/libvgm) directly, if possible.
(An open point there is the number of available channels though.)

For detailed information about a VGM, you could also try using [vgm2txt](https://github.com/vgmrips/vgmtools/blob/master/vgm2txt.c) like this: `vgm2txt "input.vgz" 0 0:00.01 "output.txt"`

VGMPlay is intended to be just a simple user interface for listening to VGM files. I'm not convinced to turn it into a file information dumping utility.

**Comment by RiedleroD** [comment]
oh, I see! thanks for the info
