### ISSUE TITLE
Linking error with MinGW

### ISSUE THREAD

**Issue by OPNA2608** [ValleyBell/vgmplay-libvgm#7]
Found while trying to write CI for this project:

> ```
> [100%] Linking CXX executable vgmplay.exe
> D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o): in function `main':
> C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain'
> collect2.exe: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/vgmplay.dir/build.make:250: vgmplay.exe] Error 1
> ```

(CI run with this error [here](https://github.com/OPNA2608/vgmplay-libvgm/runs/4342881380?check_suite_focus=true#step:6:29))

Searching for a fix online told me that adding the `-municode` linker flag is required to make GCC/MinGW use the wmain entry point. I was able to quickly fix this with the following CMake code:
```cmake
if(CMAKE_COMPILER_IS_GNUCC AND WIN32)
	target_link_libraries(${PROJECT_NAME} PRIVATE -municode)
endif()
```

(Successful CI run with this fix [here](https://github.com/OPNA2608/vgmplay-libvgm/runs/4343036821?check_suite_focus=true#step:6:27))

**Comment by ValleyBell** [comment]
Oh, that's a good catch!
I'm surprised I didn't run into that issue when doing the last round of MinGW fixes.

Fixed by 1f3afaaf130a695487130bd645b536e6cbb0aa60.
